services:
  app:
    image: radek8851/node-app:latest
    ports:
      - "3000:8080"

  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock